/*
 * Penn State Creamery Application
 */
package pennstatecreamery;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PennStateCreamery extends javax.swing.JFrame {

//Customer Entry Variables
private String firstName = "", lastName = "", street = "", streetNum = "", 
                    city = "", zipCode = "", state = "", phoneNumber = "", pinNumber = ""; 

private int validZip = 0, validPin = 0, validStreetNum = 0;
private boolean isExisting = false, nonExistingPin = false;

private DataBase db;
private Customer customer;
private DBValues dbV;
private CustomerOrder co;

    //Constructor
    public PennStateCreamery() throws SQLException, Exception {
        initComponents();
        db = new DataBase();
        dbV = new DBValues();
        customer = new Customer();
        co = new CustomerOrder();
        
        
        db.Initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        userPinField = new javax.swing.JTextField();
        createCustomerButton = new javax.swing.JButton();
        existingPinField = new javax.swing.JTextField();
        existingLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        streetNumField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        streetNumLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateField = new javax.swing.JTextField();
        zipField = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        streetNameLabel = new javax.swing.JLabel();
        streetNameField = new javax.swing.JTextField();

        jLabel6.setText("Last:");

        jLabel7.setText("First");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        createCustomerButton.setText("Create Customer");
        createCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createCustomerButtonMouseClicked(evt);
            }
        });
        createCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomerButtonActionPerformed(evt);
            }
        });

        existingLogin.setText("Login");
        existingLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                existingLoginMouseClicked(evt);
            }
        });
        existingLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("First:");

        jLabel2.setText("Last:");

        jLabel3.setText("Pin:");

        jLabel4.setText("Pin:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Existing Customer");

        jLabel8.setText("Phone:");

        streetNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNumFieldActionPerformed(evt);
            }
        });

        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });

        streetNumLabel.setText("Street Number:");

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel10.setText("Welcome to the Penn State Creamery!");

        cityLabel.setText("City:");

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        stateLabel.setText("State:");

        stateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateFieldActionPerformed(evt);
            }
        });

        zipField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipFieldActionPerformed(evt);
            }
        });

        zipLabel.setText("Zip:");

        streetNameLabel.setText("Street Name:");

        streetNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existingPinField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existingLogin)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userPinField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(streetNameLabel)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(streetNumLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityField))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createCustomerButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(10, 10, 10)
                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cityLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(zipLabel))
                                    .addComponent(stateLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetNumLabel)
                            .addComponent(streetNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(streetNameLabel)
                                    .addComponent(streetNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userPinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stateLabel)
                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zipLabel)
                        .addComponent(createCustomerButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingPinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(existingLogin))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void createCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerButtonActionPerformed
    try {
        validateEntries();
    } catch (SQLException ex) {
        Logger.getLogger(PennStateCreamery.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(PennStateCreamery.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_createCustomerButtonActionPerformed

    private void validateEntries() throws SQLException, Exception{
        //Error Check Main Entries Prior to Creating New Customer
        //In the Database
        street = streetNameField.getText().toString();
        city = cityField.getText().toString();
        zipCode = zipField.getText().toString();
        state = stateField.getText().toString();
        firstName = firstNameField.getText().toString();
        lastName = lastNameField.getText().toString();
        phoneNumber = phoneField.getText().toString();
        pinNumber = userPinField.getText().toString();
        streetNum = streetNumField.getText().toString();
        
        if(!firstName.matches("[a-zA-Z]+")){
            firstNameField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid first name entry.","Name Error", JOptionPane.ERROR_MESSAGE);
            firstNameField.setBackground(Color.white);
        }else if(!lastName.matches("[a-zA-Z]+")){
            lastNameField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid  last name entry.","Name Error", JOptionPane.ERROR_MESSAGE);
            lastNameField.setBackground(Color.white);
        }else if(!street.matches("[a-z A-Z]+")){
            streetNameField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid street name.","Address Error", JOptionPane.ERROR_MESSAGE);
            streetNameField.setBackground(Color.white);
        }else if(!phoneNumber.matches("[0-9]{10}")){
            phoneField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid phone number.\nFormat to follow: '5701234567'.","Phone Number Error", JOptionPane.ERROR_MESSAGE);
            phoneField.setBackground(Color.white);
        }else if(!pinNumber.matches("[0-9]{4}")){
            userPinField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid pin number.\nFormat to follow: '1234'.","Pin Error", JOptionPane.ERROR_MESSAGE);
            userPinField.setBackground(Color.white);
        }else if(!city.matches("[a-zA-Z]+")){
            cityField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid city.","City Error", JOptionPane.ERROR_MESSAGE);
            cityField.setBackground(Color.white);
        }else if(!zipCode.matches("[0-9]{5}")){
            zipField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid zip code.\nFormat to follow: '18650'.","Zipcode Error", JOptionPane.ERROR_MESSAGE);
            zipField.setBackground(Color.white);
        }else if(!state.matches("[a-zA-Z]{2}")){
            stateField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid state.\nFormat to follow: 'PA' or 'pa","State Error", JOptionPane.ERROR_MESSAGE);
            stateField.setBackground(Color.white);
        }else if(!streetNum.matches("[0-9]+")){
            streetNumField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid street number.","Address Error", JOptionPane.ERROR_MESSAGE);
            streetNumField.setBackground(Color.white);
        }else{
            //Parse Valid Strings to Int Values
            validZip = Integer.parseInt(zipField.getText());
            //validPhone = Double.parseDouble(phoneField.getText());
            validPin = Integer.parseInt(pinNumber);
            validStreetNum = Integer.parseInt(streetNumField.getText());
            
            //Call to Database to create new customer
            nonExistingPin = db.checkUserPin(validPin);
            
            if(nonExistingPin){
                customer.setCustomerDetails(firstName, lastName, street, validStreetNum,
                    city, state, phoneNumber, validZip, validPin);
                db.storeCustomer(customer);
                JOptionPane.showMessageDialog(null,"Customer Successfully Created!","Success", JOptionPane.INFORMATION_MESSAGE);

                setVisible(false);
                OrderFrame orderFrame = new OrderFrame(db, dbV, co, customer);

                orderFrame.setVisible(true);
            }
        }        
    }
    
    private void createCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCustomerButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createCustomerButtonMouseClicked

    private void existingLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existingLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_existingLoginMouseClicked

    private void existingLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingLoginActionPerformed
        pinNumber = existingPinField.getText().toString();
        
        //Error Check Main Entries Prior to Creating New Customer
        //In the Database        
        if(!pinNumber.matches("[0-9]{4}")){
            existingPinField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Please enter a valid pin number.","Pin Error", JOptionPane.ERROR_MESSAGE);
            existingPinField.setBackground(Color.white);
        }else{
            //Parse userPin
            validPin = Integer.parseInt(pinNumber);
            //Pull Existing Customer From Database
            
            isExisting = db.existingCustomer(customer, pinNumber);
            
            if(isExisting){
                customer.setUserPin(validPin);
                setVisible(false);
                OrderFrame orderFrame = new OrderFrame(db, dbV, co, customer);

                orderFrame.setVisible(true);
            }
        }
    }//GEN-LAST:event_existingLoginActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void streetNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNumFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void stateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateFieldActionPerformed

    private void zipFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipFieldActionPerformed

    private void streetNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PennStateCreamery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PennStateCreamery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PennStateCreamery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PennStateCreamery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PennStateCreamery().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PennStateCreamery.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(PennStateCreamery.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JButton existingLogin;
    private javax.swing.JTextField existingPinField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField stateField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetNameField;
    private javax.swing.JLabel streetNameLabel;
    private javax.swing.JTextField streetNumField;
    private javax.swing.JLabel streetNumLabel;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField userPinField;
    private javax.swing.JTextField zipField;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
}
